Myblog/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('article/', include('article.urls', namespace='article')),
    path('account/', include('account.urls', namespace='account')),
    path('album/', include('album.urls', namespace='album')),
    path('interflow/', include('interflow.urls', namespace='interflow')),
    path('mycache/',include('mycache.urls', namespace='mycache')),

]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

album/urls.py
from django.urls import path
from . import views
app_name = 'album'
urlpatterns = [
path('', views.home_view, name='home'),
path('<int:id>/', views.IndexView.as_view(), {'page': 1}, name='index_page'),
path('<int:id>/<int:page>/', views.IndexView.as_view(), name='index_page'),
path('upload/', views.upload_photo_view, name='upload_photo'),
path('test/', views.test_view, name='test'),


]

album/models.py
from django.db import models
from account.models import MyUser
# Create your models here.
class AlbumInfo(models.Model):
    id = models.AutoField(primary_key=True)
    user = models.ForeignKey(MyUser,on_delete=models.CASCADE, verbose_name='用户')
    title = models.CharField(max_length=30,blank=True,verbose_name='标题')
    introduce = models.CharField(max_length=100,blank=True,verbose_name='描述')
    photo = models.ImageField(verbose_name='图片',blank=True,upload_to='image/')

    def __str__(self):
        return f"title:{self.title},author:{self.user}"
    class Meta:
        db_table = 'album_info'
        verbose_name = '图片信息'
        verbose_name_plural = verbose_name

album/forms.py
from django import forms
from .models import AlbumInfo

class AlbumInfoForm(forms.ModelForm):
    class Meta:
        model = AlbumInfo
        fields = ['title', 'introduce', 'photo']  # 指定要包含的字段
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'introduce': forms.Textarea(attrs={'class': 'form-control'}),
            'photo': forms.FileInput(attrs={'class': 'form-control'}),
        }
        labels = {
            'title': '标题',
            'introduce': '描述',
            'photo': '图片',
        }

album/views.py
from django.http import HttpResponse
from django.views import View
from django.shortcuts import render,redirect
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.contrib.auth.decorators import login_required
from album.models import AlbumInfo
from .forms import AlbumInfoForm


# Create your views here.
def home_view(request):
    return render(request, 'home.html')
class IndexView(LoginRequiredMixin,View):
    def get(self, request,id=None,page=1):
        if id is None:
            id = request.user.id
        # 获取所有图片信息
        album_list = AlbumInfo.objects.filter(user_id=id).order_by('id')
        # 创建分页器对象
        album_obj = Paginator(album_list, 3)
        # 获取当前页的数据
        try:
            pageinfo = album_obj.page(page) # 这行代码尝试获取指定页码page的数据。
        except PageNotAnInteger:   # 如果page不是一个整数，
            pageinfo = album_obj.page(1) # 将显示第一页的数据。
        except EmptyPage:  # 请求的页码超出了有效范围
            pageinfo = album_obj.page(album_obj.num_pages) # 显示最后一页的数据。
        return render(request, 'album/album_list.html', {'pageinfo':pageinfo, 'user':request.user})


@login_required
def upload_photo_view(request):
    if request.method == 'POST':
        form = AlbumInfoForm(request.POST, request.FILES)
        if form.is_valid():
            album_info = form.save(commit=False)
            album_info.user = request.user
            album_info.save()
            return redirect('album:index_page', id=request.user.id, page=1)  # 重定向到相册首页
    else:
        form = AlbumInfoForm()
    return render(request, 'album/album_upload.html', {'form': form})



def test_view(request):
    user_id = 1
    result = AlbumInfo.objects.filter(user_id=user_id).all()
    image = result[2]
    image.delete()
    print(result)

    return HttpResponse('成功')

album/templates/album/album_list.html
{% extends 'base.html' %}
{% block title %}我的照片{% endblock %}

{% block container-fluid %}
<article>
    <a href="{% url 'article:home' %}">返回首页</a>
    <div class="picbox">
        {% if pageinfo.object_list %}
            {% for item in pageinfo.object_list %}
                <div class="photo-card">
                    <figure>
                        {% if item.photo %}
                            <img src="{{ item.photo.url }}"
                                 alt="{{ item.title|default:'相册图片' }}"
                                 class="img-fluid"
                                 width="400"
                                 height="300">

                        {% endif %}


                    </figure>
                </div>
            {% endfor %}
        {% else %}
            <p style="color: white">您还没有上传任何照片。</p>
        {% endif %}
    </div>


</article>
<div class="page_list">
        {% if pageinfo.has_previous %}
            <a href="{% url 'album:index_page' user.id pageinfo.previous_page_number %}"
               class="page-link" style="color: white">上一页</a>
        {% endif %}

        {% for page in pageinfo.paginator.page_range %}
            <a href="{% url 'album:index_page' user.id page %}"
               class="page-link {% if page == pageinfo.number %}active{% endif %}" style="color: white">
                {{ page }}
            </a>
        {% endfor %}

        {% if pageinfo.has_next %}
            <a href="{% url 'album:index_page' user.id pageinfo.next_page_number %}"
               class="page-link" style="color: white">下一页</a>
        {% endif %}
    </div>

    <a href="{% url 'album:upload_photo' %}" class="btn btn-primary">上传图片</a>
{% endblock %}

album/templates/album/album_upload.html
{% extends 'base.html' %}
{% block title %}上传照片{% endblock %}

{% block container-fluid %}
<article>
    <form method="post" enctype="multipart/form-data" action="{% url 'album:upload_photo' %}">
        {% csrf_token %}
        <p><label for="{{ form.photo.id_for_label }}" style="color: white">图片:</label>{{ form.photo }}</p>
        <button type="submit" class="btn btn-primary">上传</button>
    </form>
</article>
{% endblock %}