Myblog/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('article/', include('article.urls', namespace='article')),
    path('account/', include('account.urls', namespace='account')),
    path('album/', include('album.urls', namespace='album')),
    path('interflow/', include('interflow.urls', namespace='interflow')),
    path('mycache/',include('mycache.urls', namespace='mycache')),

]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

account/urls.py
from django.urls import path
from . import views

app_name = 'account'
urlpatterns = [
    path('', views.home_view, name='home'),
    path('<int:id>/', views.IndexView.as_view(), name='index'),
    path('login/', views.LoginView.as_view(), name='login'),
    path('register/', views.RegisterView.as_view(), name='register'),


    path('test/', views.test_view, name='test'),
    path('logout/', views.logout_view, name='logout'),





]

album/urls.py
from django.urls import path
from . import views
app_name = 'album'
urlpatterns = [
path('', views.home_view, name='home'),
path('<int:id>/', views.IndexView.as_view(), {'page': 1}, name='index_page'),
path('<int:id>/<int:page>/', views.IndexView.as_view(), name='index_page'),
path('upload/', views.upload_photo_view, name='upload_photo'),
path('test/', views.test_view, name='test'),


]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %} </title>
    <link rel="stylesheet" href="{% static 'bootstrap-5.3.3/css/bootstrap.css' %}">
    <style>
        body{
            margin: 0;
            background-image: url("{% static 'images/1356514.png' %}") ;
            background-size: cover ;
            background-repeat: no-repeat;
        }
        .header{
            background-color: #2b3035;
        }
        .header .left{
            float: left;
            color: white;
            height: 38px;
            line-height: 38px;
        }
        #starlist {
            list-style-type: none;
            padding: 0;
            margin: 0;
            display: flex;
        }
        #starlist li a{
            color: white;
            margin-right: 21px;
            text-decoration:none;
        }
        .header .right{
            float: right;
            color: white;
            height: 38px;
            line-height: 38px;
        }
        .header .right a{
            color: #b0b0b0;
            line-height: 40px;
            display: inline-block;
            font-size: 12px;
            margin-right: 21px;
            text-decoration:none;
        }
        .container-fluid .row{
            margin-top: 20px;
            color: white;
        }
        .list-group{
            background-color: transparent;
        }
        .list-group .list-group-item{
            background-color: transparent;
        }
        .media{
            margin-bottom: 30px;
        }
        .media-body{
            padding-left: 15px;
        }
        .media-left{
            vertical-align: top;
        }
        .media a {
            text-decoration:none;
        }
        .r_box{
            margin: 0 auto;
            width: 300px;
        }

        article {
            margin-bottom:20px;
        }
        .picbox{
            display: flex;
            margin-right: 20px;
        }
        .photo-card{
            margin: 50px;
        }
        .page_list {
            display: flex;
            align-items: center;
            margin-bottom: 20px;
        }
        .page_list a{
            margin-right: 20px;
        }
        .right-text{
            margin-top: 100px;
            text-decoration: none;
        }
        .right-text h1{
            border-bottom: 1px solid white;
            font-size: 3rem;
            text-shadow: 5px 5px 5px darkolivegreen, 2px 2px 1px darkolivegreen;
        }
        .right-text span{
             background-color: darkolivegreen;

        }
        .right-text a{
            color: darkolivegreen;
            text-decoration: none;
        }
        .right-text button{
            background-color: transparent;
        }
    </style>
</head>
<body>
{% block header %}{% endblock %}
{% block container-fluid %}{% endblock container-fluid %}

<script src="{% static 'js/jquery-3.7.1.min.js' %}"></script>
<script src="{% static 'bootstrap-5.3.3/js/bootstrap.js' %}"></script>
</body>
</html>

templates/footer.html
<nav aria-label="Page navigation" class="mt-4">
    <ul class="pagination justify-content-start"> {# start把位置设置在左边 #}
        {% if page_obj.has_previous %}
        <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
                <i class="page-item">Previous</i>
            </a>
        </li>
        {% endif %}

        {% for num in page_obj.paginator.page_range %}
        <li class="page-item {% if num == page_obj.number %}active{% endif %}">
            <a class="page-link" href="?page={{ num }}">{{ num }}</a>
        </li>
        {% endfor %}

        {% if page_obj.has_next %}
        <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.next_page_number }}">
                <i class="page-item">Next</i>
            </a>
        </li>
        {% endif %}
    </ul>
</nav>

templates/home.html
{% extends 'base.html' %}

{% block title %}我的博客{% endblock %}
{% block header %}

<div class="header">
    <div class="container">

        <div class="left">
            <ul id="starlist">
                {% if user.is_authenticated %}
                    <li><a href="{% url 'article:index' user.id %}">我的日记</a></li>
                    <li><a href="{% url 'album:index_page' user.id %}">我的相册</a></li>
                    <li><a href="{% url 'account:index' user.id %}">关于我</a></li>
                    <li><a href="{% url 'interflow:index' user.id %}">留言</a></li>
                {% endif %}
            </ul>
        </div>

        <div class="right">
            {% if user.is_authenticated %}
                {# 登录状态显示退出链接 #}
                <a href="{% url 'account:logout' %}">退出</a>
            {% else %}
                {# 未登录状态显示注册/登录 #}
                <a href="{% url 'account:login' %}">登录</a>
                <a href="{% url 'account:register' %}">注册</a>
            {% endif %}
        </div>
        <div style="clear: both"></div>
    </div>
</div>
{% endblock header %}

{% block container-fluid %}
    <div class="container-fluid">
        <div class="row">

            <div class="col-sm-9">
                {% include 'left.html' %}

            </div>

            <div class="col-sm-3">
                {% include 'right.html' %}
            </div>
        </div>


    </div>

{% endblock container-fluid %}

templates/left.html
{% for article in page_obj %}
<div class="media article-item mb-4">


    <div class="media-body">
        <h4 class="media-heading article-title">
            <a href="#" style="color: white">{{ article.title }}</a>
        </h4>

        <div class="article-meta mb-2">
            <span class="text-muted">
                <i style="color: white">{{ article.author.username }}</i>
            </span>
            <span class="text-muted mx-2">|</span>
            <span class="text-muted">
                <i class="fas fa-clock" style="color: white">{{ article.created|date:'Y-m-d H:i' }}</i>
            </span>
            {% if article.article_tag.exists %}
            <span class="text-muted mx-2">|</span>
            <span class="article-tags">
                <i class="fas fa-tags"></i>
                {% for tag in article.article_tag.all %}
                <span class="badge badge-secondary">{{ tag.tag }}</span>
                {% endfor %}
            </span>
            {% endif %}
        </div>

        <div class="article-content" style=" color: white">
            {{ article.content }}
        </div>
    </div>
</div>

{% endfor %}
<div class="footer">
    {% include 'footer.html' %}
</div>

templates/right.html
<div class="right-text">
    <h1>Notice  Board</h1>
    <div class="job-title"><h5 style="padding-left: 200px">--Web developers</h5></div>
    <p>
        Far far away, behind the word mountains, far from the countries <span>Infiltration</span> and
        <span>Hacker</span>, there live the blind texts. Separated they live in Bookmarksgrove
        right at the coast of the Semantics, a large language ocean.
    </p>

    <p>
        A small river named <span>Black-box flows by their place and supplies it with
        the necessary regelialia.</span> <br>It is a paradisematic country, in which roasted parts of
        sentences fly into your mouth.
    </p>

    <h2>Contact information</h2>
    <ul>
        <li>Email: <a href="mailto:paulken731@gmail.com">Administrator@gmail.com</a></li>
        <li>Web: <a href="https://github.com/kenichi-lover">https://github.com</a></li>
        <li>Tel:
            <button style="color: white">Press me</button>
            <div id="greeting"></div>
        </li>
    </ul>
</div>
<script>
    const button = document.querySelector("button");

    function greet() {
        const name = prompt("What is your name?");
        const greeting = document.querySelector("#greeting");
        greeting.textContent = `Hello ${name}, nice to see you! my phone number is 13807391908`;
    }

    button.addEventListener("click", greet);
</script>